global_frame: lidar_odom
rolling_window: true
track_unknown_space: true
robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5
resolution: 0.05

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

obstacles_laser:
  observation_sources: lidar
  lidar: 
    data_type: PointCloud2
    clearing: true
    marking: true
    topic: /velodyne_points
    inf_is_valid: true
    min_obstacle_height: 0.5
    max_obstacle_height: 2.5


inflation:
  inflation_radius: 1.0