local_costmap_rgbd_front:
  plugins:
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  global_frame: soma_link
  robot_base_frame: soma_link
  transform_tolerance: 0.5
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.1
  update_frequency: 3.0
  publish_frequency: 3.0
  always_send_full_costmap: false
  max_obstacle_height: 5.0
  obstacle_range: 0.0
  conbination_method: 0


  obstacle_layer:
    observation_sources: rgbd_f
    rgbd_f:
      sensor_frame: soma_link
      topic: depth_registered/filtered_points
      data_type: PointCloud2
      marking: true
      clearing: true
      min_obstacle_height: -1.0