local_costmap_rgbd_front:
  plugins:
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  global_frame: soma_link
  robot_base_frame: soma_link
  rolling_window: true
  width: 12.0
  height: 8.0
  resolution: 0.1
  update_frequency: 3.0
  publish_frequency: 3.0

  obstacle_layer:
    observation_sources: rgbd_f
    rgbd_f:
      sensor_frame: camera_F_link
      topic: /depth_registered/filtered_points
      data_type: PointCloud2
      marking: true
      clearing: true
      min_obstacle_height: 0.0