global_costmap:
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
  global_frame: map
  robot_base_frame: soma_link
  update_frequency: 2.0
  publish_frequency: 2.0

  static_layer:
    map_topic: "mymap" # should set same of SLAM output
    track_unknown_space: false
    subscribe_to_updates: true