local_costmap:
  plugins: 
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
  global_frame: odom
  robot_base_frame: base_link
  rolling_window: true
  width: 15.0
  height: 15.0
  origin_x: 0.0
  origin_y: 0.0
  resolution: 0.05
  update_frequency: 3.0
  publish_frequency: 3.0
  transform_tolerance: 5.0

  obstacle_layer:
    observation_sources: scan
    scan: 
      sensor_frame: base_link
      topic: /camera_f/scan
      data_type: LaserScan
      marking: true
      clearing: true
      obstacle_range: 6.0
      ray_trace_range: 6.5
      obstacle_min_z: 1.0
      obstacle_max_z: 2.5
    lidar:
      sensor_frame: base_link
      topic: /velodyne_points
      data_type: PointCloud2
      marking: true
      clearing: true
      obstacle_range: 5.0
      ray_trace_range: 5.5
      obstacle_min_z: 0.5
      obstacle_max_z: 2.5
        
  inflation_layer:
    inflation_radius: 0.5