local_costmap:
  plugins: 
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
  global_frame: odom
  robot_base_frame: soma_link
  rolling_window: true
  width: 10.0
  height: 10.0
  origin_x: 0.0
  origin_y: 0.0
  resolution: 0.05
  update_frequency: 3.0
  publish_frequency: 3.0
  transform_tolerance: 5.0

  obstacle_layer:
    observation_sources: scan lidar
    scan: 
      sensor_frame: camera_f_link
      topic: /camera_f/scan
      data_type: LaserScan
      marking: true
      clearing: true
      obstacle_range: 5.0
      ray_trace_range: 5.5
      # obstacle_min_z: -0.5
    lidar:
      sensor_frame: velodyne
      topic: /velodyne_points
      data_type: PointCloud2
      marking: true
      clearing: true
      obstacle_range: 5.0
      ray_trace_range: 5.5
      # obstacle_min_z: -0.5
        
  inflation_layer:
    inflation_radius: 0.1