topics:
  - name: joy_cmd
    topic: /joy_teleop/cmd_vel
    timeout: 0.5
    priority: 10

  - name: nav_cmd
    topic: /soma/cmd_vel
    timeout: 0.5
    priority: 100

locks:
  - name: e_stop
    topic: e_stop
    timeout: 0.0
    priority: 255
