# for visual odometry and imu fusion

frequency: 10
sensor_timeout: 1.0
two_d_mode: false
transform_time_offset: 0.0
transform_time_out: 0.0
print_diagnostics: true
publish_tf: true
publish_acceleration: false

world_frame: vodom
# map_frame: map
odom_frame: vodom
base_link_frame: soma_link

#odom0: visual odometry
odom0: vodom
odom0_config: [true, true, true,
               true, true, true,
               false, false, false,
               true, true, true,
               false, false, false]

#imu0: imu data
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              true, false, false]